# -*- coding: utf-8 -*-
"""DIP 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kC2F1deylDj6_A6ZROotQFKQ83ITLjGy
"""

#Description : This script wwould classify satellite images

#Import the libraries
import tensorflow as tf 
from tensorflow import keras
from keras.models import Sequential
from keras.layers import Dense, Flatten, Conv2D, MaxPooling2D, Dropout
from tensorflow.keras import layers
from keras.utils import to_categorical
import numpy as np
import matplotlib.pyplot as plt
plt.style.use ('fivethirtyeight')